imports:
  - { resource: parameters.dist.yml }

services:
  dbal:
    class: Doctrine\DBAL\Connection
    factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
    arguments: ['%db%']

  clear:
    class: Efko\PurgeLog\Service\ClearService
    arguments: ['@dbal']