parameters:
  db:
    url: 'mysql://user:password@localhost:3306/tableName?charset=utf8'

services:
  dbal:
    class: Doctrine\DBAL\Connection
    factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
    arguments: ['%db%']

  clear:
    class: Efko\PurgeLog\Service\ClearService
    arguments: ['@dbal']